language: android
before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-21"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - chmod +x gradlew
  - sdkmanager tools
  # Install the system image
  - sdkmanager "system-images;android-18;default;armeabi-v7a
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install: ./gradlew clean assemble assembleAndroidTest --stacktrace

android:
        components:
                - tools
                - platform-tools
                - build-tools-27.0.2
                - build-tools-26.0.2
                - android-27
                - tools
                - extra
                - extra-android-support
                - extra-android-m2repository
                - extra-google-m2repository
                - sys-img-armeabi-v7a-android-21
        licenses:
                - 'android-sdk-license-.+'

jdk:
        - oraclejdk8

notifications:
        email: false

sudo: false

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

script:
  - android list target
  - ./gradlew connectedAndroidTest

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

cache:
  directories:
    - $HOME/.gradle