language: android
before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew
android:
        components:
                - tools
                - platform-tools
                - build-tools-27.0.2
                - build-tools-26.0.2
                - android-27
                - tools
                - extra
                - extra-android-support
                - extra-android-m2repository
                - extra-google-m2repository
                - sys-img-armeabi-v7a-android-21

jdk:
        - oraclejdk8

notifications:
        email: false

sudo: false

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

cache:
  directories:
    - $HOME/.gradle