language: android
before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew
android:
        components:
                - tools
                - platform-tools
                - build-tools-27.0.2
                - android-27
                - tools
                - extra
                - extra-android-support
                - extra-android-m2repository
                - extra-google-m2repository

jdk:
        - oraclejdk8

notifications:
        email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle